// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '../validation/index.js';
import { Type } from 'class-transformer';
import { IsArray, IsObject, IsString, ValidateNested } from 'class-validator';

/**
 * Generic configuration for secrets.
 */
export class CausaSecrets {
  constructor(init: CausaSecrets) {
    Object.assign(this, init);
  }

  /**
   * The ID of the default backend to use when fetching secrets, if none is specified.
   */
  @AllowMissing()
  @IsString()
  readonly defaultBackend?: string;

  [key: string]: any;
}

/**
 * Configuration for the CLI itself.
 */
export class Causa {
  constructor(init: Causa) {
    Object.assign(this, init);
  }

  /**
   * The modules to load when the CLI runs.
   * Keys are the names of the modules (npm packages) and values are semver versions.
   * Local paths are also accepted. Relative paths will be resolved from the workspace root.
   */
  @AllowMissing()
  @IsObject()
  readonly modules?: Record<string, string>;

  /**
   * Generic configuration for secrets.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => CausaSecrets)
  @ValidateNested()
  readonly secrets?: CausaSecrets;

  [key: string]: any;
}

export class EnvironmentConfiguration {
  constructor(init: EnvironmentConfiguration) {
    Object.assign(this, init);
  }

  /**
   * The full displayable name for the environment.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  /**
   * Additional configuration that will be merged with the main one before running operations against the
   * environment.
   */
  @AllowMissing()
  @IsObject()
  readonly configuration?: Record<string, any>;

  [key: string]: any;
}

/**
 * Information about the project within the workspace.
 * The file defining `project.name` should be located at the root of the project.
 * Its location will be used to determine the project path.
 */
export class Project {
  constructor(init: Project) {
    Object.assign(this, init);
  }

  /**
   * The name of the project.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  /**
   * The type of project.
   */
  @AllowMissing()
  @IsString()
  readonly type?: string;

  /**
   * The programming language for the project.
   */
  @AllowMissing()
  @IsString()
  readonly language?: string;

  /**
   * A description for the project.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * A list of glob patterns, relative to the workspace root, that match files or directories that are also part
   * of the project.
   * This is only needed for files or directories that are not part of the project root.
   * This is a hint to various processes (e.g. project changes detection, linting, etc.) that they should also
   * consider those files and directories when running operations against the project.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly externalFiles?: string[];

  [key: string]: any;
}

export class SecretConfiguration {
  constructor(init: SecretConfiguration) {
    Object.assign(this, init);
  }

  /**
   * The ID of the backend to use when fetching the secret.
   * Defaults to `causa.secrets.defaultBackend`.
   */
  @AllowMissing()
  @IsString()
  readonly backend?: string;

  [key: string]: any;
}

/**
 * Information about the workspace.
 * The file defining `workspace.name` should be located at the root of the workspace.
 * Its location will be used to determine the root path.
 */
export class Workspace {
  constructor(init: Workspace) {
    Object.assign(this, init);
  }

  /**
   * The name of the workspace.
   * Depending of the size, it could be the name of the company, or the overarching project.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  /**
   * A description for the workspace.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  [key: string]: any;
}

/**
 * The schema for core elements of the configuration.
 */
export class BaseConfigurationSchema {
  constructor(init: BaseConfigurationSchema) {
    Object.assign(this, init);
  }

  /**
   * Information about the workspace.
   * The file defining `workspace.name` should be located at the root of the workspace.
   * Its location will be used to determine the root path.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Workspace)
  @ValidateNested()
  readonly workspace?: Workspace;

  /**
   * Information about the project within the workspace.
   * The file defining `project.name` should be located at the root of the project.
   * Its location will be used to determine the project path.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Project)
  @ValidateNested()
  readonly project?: Project;

  /**
   * Configuration for the CLI itself.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Causa)
  @ValidateNested()
  readonly causa?: Causa;

  /**
   * A map where keys are secret IDs and values are the corresponding configurations.
   * The configuration may contain fields that are specific to the referenced backend.
   */
  @AllowMissing()
  @IsObject()
  readonly secrets?: Record<string, SecretConfiguration>;

  /**
   * A map where keys are environment IDs and values provide details about each environment.
   */
  @AllowMissing()
  @IsObject()
  readonly environments?: Record<string, EnvironmentConfiguration>;

  [key: string]: any;
}
